on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrsmachew.azurecr.io
        username: ${{ secrets.acr_acrsmachew_username }}
        password: ${{ secrets.acr_acrsmachew_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrsmachew.azurecr.io/akssmachew:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrsmachew.azurecr.io/akssmachew:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akssmachew_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-smachewab8d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-smachewab8d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-smachewab8d
        container-registry-url: acrsmachew.azurecr.io
        container-registry-username: ${{ secrets.acr_acrsmachew_username }}
        container-registry-password: ${{ secrets.acr_acrsmachew_password }}
        secret-name: akssmachewdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-smachewab8d
        manifests: |
          manifests/deployment-8.yml
          manifests/service-8.yml
        images: |
          acrsmachew.azurecr.io/akssmachew:${{ github.sha }}
        imagepullsecrets: |
          akssmachewdockerauth
